### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by GKrizz**
Created Read me

### CODE REVIEW

**Comment by sanjeevidev** [comment]
> Created Read me 

Needed the Functionality of this project and the working refer:GitHub.com/sanjeevidev/Flask-Openai

**Comment by sanjeevidev** [comment]
> > Created Read me 
> 
> Needed the Functionality of this project and the working 😅😅
refer: https://github.com/sanjeevidev/Flask-Openai

**Comment by sanjeevidev** [comment]
> Created Read me 

Needed the Functionality and working of the Project 😅
Refer : https://github.com/sanjeevidev/Flask-Openai

**Review by 21CB46 — CHANGES_REQUESTED** [review]
/

**Pull request merged**
